spring:
  profiles:
    group:
      dev: "dev, common"
      prod: "prod, common"
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:h2:mem:mogakco;MODE=MYSQL;NON_KEYWORDS=USER"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      auth:
        host: localhost
        port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
cors:
  origin: "http://localhost:3000"
app:
  host:
    server: http://localhost:8080
    client: http://localhost:3000
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: common
  threads:
    virtual:
      enabled: true